# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo/zybo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo || ORIG_REF_NAME==zybo}]

# IP: bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_processing_system7_0_0 || ORIG_REF_NAME==zybo_processing_system7_0_0}]

# IP: bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_0 || ORIG_REF_NAME==zybo_axi_gpio_0_0}]

# IP: bd/zybo/ip/zybo_processing_system7_0_axi_periph_0/zybo_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zybo_processing_system7_0_axi_periph_0}]

# IP: bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zybo_rst_processing_system7_0_100M_0}]

# IP: bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_1 || ORIG_REF_NAME==zybo_axi_gpio_0_1}]

# IP: bd/zybo/ip/zybo_xbar_0/zybo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_xbar_0 || ORIG_REF_NAME==zybo_xbar_0}]

# IP: bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_2 || ORIG_REF_NAME==zybo_axi_gpio_0_2}]

# IP: bd/zybo/ip/zybo_auto_pc_0/zybo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_auto_pc_0 || ORIG_REF_NAME==zybo_auto_pc_0}]

# XDC: bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_processing_system7_0_0 || ORIG_REF_NAME==zybo_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_0 || ORIG_REF_NAME==zybo_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0_ooc.xdc

# XDC: bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_0 || ORIG_REF_NAME==zybo_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zybo_rst_processing_system7_0_100M_0}]

# XDC: bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zybo_rst_processing_system7_0_100M_0}]

# XDC: bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_1 || ORIG_REF_NAME==zybo_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1_ooc.xdc

# XDC: bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_1 || ORIG_REF_NAME==zybo_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/zybo/ip/zybo_xbar_0/zybo_xbar_0_ooc.xdc

# XDC: bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_2 || ORIG_REF_NAME==zybo_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2_ooc.xdc

# XDC: bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_axi_gpio_0_2 || ORIG_REF_NAME==zybo_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/zybo/ip/zybo_auto_pc_0/zybo_auto_pc_0_ooc.xdc

# XDC: bd/zybo/zybo_ooc.xdc
