# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.cache/wt [current_project]
set_property parent.project_path /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/zybo.bd
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_0/zybo_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_rst_processing_system7_0_100M_0/zybo_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_1/zybo_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_xbar_0/zybo_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_axi_gpio_0_2/zybo_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/ip/zybo_auto_pc_0/zybo_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/zybo_ooc.xdc]
set_property is_locked true [get_files /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/zybo.bd]

read_verilog -library xil_defaultlib /home/petalinux/emblnx/labs/bsp_generation/hardware/ZYBO-2015.4.srcs/sources_1/bd/zybo/hdl/zybo_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top zybo_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef zybo_wrapper.dcp
catch { report_utilization -file zybo_wrapper_utilization_synth.rpt -pb zybo_wrapper_utilization_synth.pb }
